apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitops-foundations
  namespace: flagger-exercise
  labels:
    app: gitops-foundations
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: johnsonmd.australiaeast.cloudapp.azure.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service: gitops-foundations-service
              port:
                number: 80
